name: Deploy to cPanel via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy via SFTP with Key
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: shift7store.com
          username: shiftsto
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          local_path: ./dist/*
          remote_path: /home/shiftsto/public_html
          sftp_only: true
